### PR TITLE
DEV-44

### PR DESCRIPTION
**Pull request by UrielOfir**
I added buttons with icons for taking care of the tamaguchi

### CODE REVIEW

**Review by Denice-S — CHANGES_REQUESTED** [review]
Hi Uriel, 

Buttons look great,  could I ask for a small change to be made please?

You have added the style `style=font-size:28px;`

Font awesome has its own sizing for the size of the icons, which are all relative sizing classes. (https://fontawesome.com/how-to-use/on-the-web/styling/sizing-icons) 

Please can you remove the style : ` style=font-size:28px;`  from the HTML and just add in the most appropriate font awesome class size please?

**Comment by UrielOfir** [comment]
I changed the icons as you asked

**Review by onlyasmalllizard — CHANGES_REQUESTED** [review]
Hi Uriel, the buttons look good! Could you please move the meta tags and stylesheet link tags back inside the head tag? Thank you!

**Comment by UrielOfir** [comment]
I moved the tags

**Review by onlyasmalllizard — APPROVED** [review]
Great, thank you!

**Pull request merged**
